# Generated by Django 5.1.2 on 2024-10-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_user_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
