# Generated by Django 5.1.1 on 2024-11-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
