# Generated by Django 5.1.1 on 2024-10-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to='profile_pictures/'),
        ),
    ]
