# Generated by Django 5.1 on 2024-11-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_customuser_pnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pnumber',
            field=models.CharField(default='+1234567890', max_length=13, unique=True),
        ),
    ]
