# Generated by Django 5.1.1 on 2024-10-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
