# Generated by Django 5.1.1 on 2024-11-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_profile_birthday_profile_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
