# Generated by Django 5.1.1 on 2024-10-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='PNS', max_length=50),
        ),
    ]
