# Generated by Django 5.1.1 on 2024-11-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
