# Generated by Django 5.1.1 on 2024-10-31 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('adminUsers', models.ManyToManyField(related_name='team_admin_Users', to=settings.AUTH_USER_MODEL)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_sent_emails', to=settings.AUTH_USER_MODEL)),
                ('memberUsers', models.ManyToManyField(related_name='team_member_Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamEmailFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('emailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamEmails.teamemail')),
            ],
        ),
        migrations.CreateModel(
            name='TeamReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('emailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_emialReply', to='TeamEmails.teamemail')),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_reply_to_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamReplyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('emailId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_emialReplyFiles', to='TeamEmails.teamemail')),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_reply_files_user', to=settings.AUTH_USER_MODEL)),
                ('replyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_reply_file_replyid', to='TeamEmails.teamreply')),
            ],
        ),
    ]
