# Generated by Django 5.1.1 on 2024-10-02 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailCompositionAndManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUser', models.CharField(max_length=100)),
                ('toUser', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
                ('emialId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmailCompositionAndManagement.email')),
            ],
        ),
    ]
