# Generated by Django 5.1.1 on 2024-10-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailCompositionAndManagement', '0002_emailfiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailfiles',
            old_name='emialId',
            new_name='emailId',
        ),
    ]
