# Generated by Django 5.1.1 on 2024-10-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailCompositionAndManagement', '0003_rename_emialid_emailfiles_emailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
