# Generated by Django 5.1.1 on 2024-10-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailCompositionAndManagement', '0004_temporaryuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='EmailCompositionAndManagement.temporaryuser'),
        ),
        migrations.AlterField(
            model_name='email',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_emails', to='EmailCompositionAndManagement.temporaryuser'),
        ),
        migrations.AlterField(
            model_name='emailfiles',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emailFiles', to='EmailCompositionAndManagement.temporaryuser'),
        ),
        migrations.AlterField(
            model_name='emailfiles',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_emailFiles', to='EmailCompositionAndManagement.temporaryuser'),
        ),
    ]
