# Generated by Django 5.1.1 on 2024-10-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailCompositionAndManagement', '0006_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_files_user', to='EmailCompositionAndManagement.temporaryuser')),
                ('replyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_file_replyid', to='EmailCompositionAndManagement.reply')),
            ],
        ),
    ]
