# Generated by Django 5.1.1 on 2024-10-15 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailCompositionAndManagement', '0007_replyfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyfiles',
            name='emailId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emialReplyFiles', to='EmailCompositionAndManagement.email'),
        ),
    ]
