# Generated by Django 5.1.1 on 2024-10-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailCompositionAndManagement', '0008_replyfiles_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
