# Generated by Django 5.1.1 on 2024-10-31 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailCompositionAndManagement', '0009_email_isdeleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailfiles',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emailFiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailfiles',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_emailFiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
