# Generated by Django 5.1.1 on 2024-10-31 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailCompositionAndManagement', '0010_alter_email_fromuser_alter_email_touser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_email', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='replyfiles',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_files_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
